tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "warm-copper": "#994E14",
        "golden-ochre": "#C79242",
        "peach-cream": "#FFE3BA",
        "vanilla-cream": "#FFF1DB",
        ink: "#1A0C04",
        primary: "#994E14",
        secondary: "#C79242",
        background: "#FFF1DB",
        surface: "#FFF1DB",
        "surface-container": "#FFE3BA",
        "on-surface": "#1A0C04",
        "on-background": "#1A0C04",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#5c4a3a",
        "primary-container": "#1A0C04",
        "on-primary-container": "#FFE3BA",
        "secondary-container": "#FFE3BA",
        "on-secondary-container": "#1A0C04",
        outline: "#8a7460",
        "outline-variant": "#d9c4a8",
        "surface-variant": "#F3E2C8",
        "surface-container-low": "#FFF6E8",
        "surface-container-high": "#F3E2C8",
        "surface-container-highest": "#EAD4B4",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#FFF1DB",
        "surface-dim": "#E6D3B4",
        "inverse-surface": "#1A0C04",
        "inverse-on-surface": "#FFF1DB",
        "inverse-primary": "#E8B56A",
        tertiary: "#1A0C04",
        "tertiary-container": "#3A2800",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#C79242",
        "tertiary-fixed": "#ffdea5",
        "tertiary-fixed-dim": "#e9c176",
        "on-tertiary-fixed": "#261900",
        "on-tertiary-fixed-variant": "#5d4201",
        "primary-fixed": "#F3D3A8",
        "primary-fixed-dim": "#E8B56A",
        "on-primary-fixed": "#1A0C04",
        "on-primary-fixed-variant": "#994E14",
        "secondary-fixed": "#f2e0c3",
        "secondary-fixed-dim": "#d5c5a8",
        "on-secondary-fixed": "#1A0C04",
        "on-secondary-fixed-variant": "#6d614a",
        "surface-tint": "#994E14",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "margin-desktop": "80px",
        "section-gap": "72px",
        "margin-mobile": "16px",
        unit: "8px",
        gutter: "32px",
        "container-max": "1440px"
      },
      fontFamily: {
        "display-lg": ["Playfair Display", "Georgia", "serif"],
        "headline-lg": ["Playfair Display", "Georgia", "serif"],
        "headline-md": ["Playfair Display", "Georgia", "serif"],
        "headline-sm": ["Playfair Display", "Georgia", "serif"],
        "headline-lg-mobile": ["Playfair Display", "Georgia", "serif"],
        "body-md": ["Montserrat", "system-ui", "sans-serif"],
        "body-lg": ["Montserrat", "system-ui", "sans-serif"],
        "label-caps": ["Montserrat", "system-ui", "sans-serif"]
      }
    }
  }
};
